config/routes.rb
Rails.application.routes.draw do
  root 'home#index', :as => :home
  get 'about' => 'home#about'
  resources :friends
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<!-- เปลี่ยน พื้นหลังของ Header เป็นสีดำ -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <!-- เปลี่ยนชื่อ Navigator Bar -->
    <a class="navbar-brand" href="#">Friends App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <!-- ใช้ Helper เพื่อสร้างลิงค์ Home แทน static path -->
          <%= link_to "Home", home_path, class: "nav-link" %>
        </li>
        <!-- Embedded ruby เพื่อตรวจสอบและแสดงโค้ดส่วนนี้เมื่อ Sign in แล้วเท่านั้น -->
        <% if user_signed_in? %>
          <li class="nav-item">
            <!-- ลิงค์ไปหน้า Sign out  -->
            <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <!-- ลิงค์ไปหน้า Edit user  -->
            <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <!-- ลิงค์ไปหน้า Sign up  -->
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <!-- ลิงค์ไปหน้า Sign in  -->
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <!-- ใช้ Helper เพื่อสร้างลิงค์ About แทน static path -->
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </ul>
    </div>
  </div>
</nav>